### ISSUE TITLE
Not comparable with 47.1?

### ISSUE THREAD

**Issue by Matrixpower** [daneden/sketch-collapse-all#10]
First of all, thank you so much for making this plugin. It saves a ton of my time!
I installed the latest plugin to Sketch 47.1 and found that the shortcut (CMD + E on Mac) doesn't work. Any suggestion if it should work with the latest Sketch?

Thanks!

**Comment by olivier-w** [comment]
Same issue for me, but you can get around it by adding a shortcut in `System Preferences > Keyboard > Shortcuts > App Shortcuts`:

![screen shot 2017-10-25 at 3 46 34 pm](https://user-images.githubusercontent.com/465250/32019609-ce88e6d8-b99b-11e7-88b6-c68f0dd8ce7f.png)

![screen shot 2017-10-25 at 3 47 41 pm](https://user-images.githubusercontent.com/465250/32019640-e05762f4-b99b-11e7-9ae6-e886d633ae6b.png)

**Comment by florianpeninon** [comment]
The conflict comes from an update on Sketch side of the export shortcut, overriding it in the system setting will make you lose the shortcut for export.

I pushed a PR with a new version that includes a change in shortcut : https://github.com/daneden/sketch-collapse-all/pull/9

**Comment by olivier-w** [comment]
I can still export using `cmd-shift-e`, so I don't mind this workaround to use the default `cmd-e` that Dan defined.

![screen shot 2017-10-26 at 1 10 57 pm](https://user-images.githubusercontent.com/465250/32066889-4294824a-ba4f-11e7-8a7c-47eb68255196.png)

**Comment by daneden** [comment]
Fixed in #9
