### ISSUE TITLE
Broken in Sketch 4.3

### ISSUE THREAD

**Issue by ghost** [daneden/sketch-collapse-all#3]
Sketch was updated today to 4.3 (April 6th) and it looks like this plugin has broken. 

I've restarted and un-installed/re-installed and the issue persists. 

It just doesn't do anything when running the plugin.

**Comment by ghost** [comment]
Just realised Sketch has this built in now, just need to assign a shortcut to it.

**Comment by daneden** [comment]
@sixtyfourthirtytwo thanks for alerting this bug to me! The menu item was always there, I just built a plugin for convenience. I've just pushed a fix, it should now work in v43.
