### ISSUE TITLE
Not working with Sketch 45

### ISSUE THREAD

**Issue by AnaghSharma** [daneden/sketch-collapse-all#6]
Just tried the plugin with Sketch Version 45 (43475) and it is not working at all.

**Comment by jaredcommonmedia** [comment]
Me neither... cmd+E pulls up "Sketch Constraints".

**Comment by AnaghSharma** [comment]
@jaredcommonmedia For me cmd + E does nothing.

**Comment by elliottmangham** [comment]
I'd like to bump this issue. @daneden will there be an update for Sketch 45+?

I literally cannot live without this plugin, it has became so useful!

Thanks,

**Comment by daneden** [comment]
Fixed in #5.
