### ISSUE TITLE
Not working with Sketch 47

### ISSUE THREAD

**Issue by TedGoas** [daneden/sketch-collapse-all#8]
Seems this plugin doesn't work in the latest Sketch update, Version 47 (45396).

**Comment by elliottmangham** [comment]
+1 same problem

**Comment by florianpeninon** [comment]
@TedGoas @elliottmangham I don't think the plugin itself is the problem, `cmd + e` is now a native shortcut. Using the plugin via the menu still works.

**Comment by TedGoas** [comment]
@florianpnn ahh, so it does!

**Comment by florianpeninon** [comment]
I fixed it on a fork and submitted a PR, you can get it here : https://github.com/florianpnn/sketch-collapse-all/tree/update-shortcut

**Comment by elliottmangham** [comment]
@florianpnn, hi! This doesn't work for me. Both `⌘ + ctrl + c` or `⌘ + e`... It only works by using the plugin via the menu.

Thanks a lot!

![screen shot 2017-10-25 at 12 35 32](https://user-images.githubusercontent.com/12933804/31996607-05dd1df4-b981-11e7-8315-428fb3b78965.png)

**Comment by davidbograd** [comment]
same here! would be awesome with a fix

**Comment by florianpeninon** [comment]
@elliottmangham did you overwrite @daneden version with mine?

Here's what I have on my side
![image](https://user-images.githubusercontent.com/2725387/32053283-23a47db6-ba5b-11e7-9d1d-ed3a8c114dad.png)

**Comment by daneden** [comment]
Fixed in #9
